### ISSUE TITLE
Too many git clones in a second causing errors

### ISSUE THREAD

**Issue by ywei2017** [mmb/concourse-bitbucket-pullrequest-resource#17]
Hi, Our internal BitBucket server returns "too many requests" due to a rate limiting plugin that is used. 

One way to solve it, is to put in a "sleep xx" between the pulling down of each PR. Do you see that as a valid approach? If so I can work it out and put in a P/R to be reviewed.

Thanks
Yansheng

**Comment by ywei2017** [comment]
@mmb Can you kindly respond?

Thanks
Yansheng

**Comment by mmb** [comment]
You can reduce the polling interval in Concourse or you can use Concourse webhooks instead of polling.

**Comment by ywei2017** [comment]
Hi, @mmb ,I tried to reduce the "check" frequency to a reasonable level. The remaining problem is, everytime a check occurs, it tries to retrieve all the PRs in the [while loop](https://github.com/mmb/concourse-bitbucket-pullrequest-resource/blob/4232a80916fd39274126dc65b5eecb45c914c442/assets/check#L85), and that causes our bitBucket server's rate limiting feature to kick in.  My thought is that a simple configurable/optional sleep in the while loop will make it more friendly.

**Comment by ywei2017** [comment]
@mmb See [PR 18](https://github.com/mmb/concourse-bitbucket-pullrequest-resource/pull/18). I think code actually explains better than my wording.

Thanks
Yansheng

**Comment by ywei2017** [comment]
hi, @mmb Do you also maintain the [docker image](https://hub.docker.com/r/mm62/concourse-bitbucket-pullrequest-resource)?  I wondering whether I should build the container myself, or I can just mirror from docker hub.

Thanks
Yansheng

**Comment by mmb** [comment]
I just updated that docker image.

**Comment by ywei2017** [comment]
Thank you @mmb , amazing how much you get simply by asking :-)

Cheers,
Yansheng
